version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: drug_search_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pharmacy_db
    ports:
      - "5430:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d pharmacy_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
  fastapi:
    build: .  # Использует Dockerfile из текущей директории
    container_name: drug_search_api
    ports:
      - "8000:8000"
    command: python3 asgi.py
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@db:5432/pharmacy_db"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped


volumes:
  pg_data:
  pg_test_data: